# Generated by Django 5.2.7 on 2025-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
