# Generated by Django 5.2.7 on 2025-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_pokemon', '0002_alter_pokemon_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
