# Generated by Django 5.2.7 on 2025-10-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_pokemon', '0003_pokemon_height_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evoluciones',
            field=models.ManyToManyField(blank=True, related_name='pre_evoluciones', to='listado_pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
